---
apiVersion: v1
kind: Service
metadata:
  name: kfk-svc
  labels:
    app: kfk-svc
    category: kafka    
spec:
  ports:
  - name: server
    protocol: TCP  
    port: 9092
  clusterIP: None
  selector:
    app: kfk