---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
  namespace: kafka
  labels:
    category: zookeeper
spec:
  selector:
    matchLabels:
      app: zk
  minAvailable: 2