---
apiVersion: v1
kind: Service
metadata:
  name: zk-svc
  labels:
    app: zk-svc
    category: zookeeper
spec:
  ports:
  - name: client
    protocol: TCP  
    port: 2181
  - name: server
    protocol: TCP  
    port: 2888
  - name: leader-election
    protocol: TCP  
    port: 3888
  clusterIP: None
  selector:
    app: zk