---
version: '3'
services:
  zk:
    image: mbe1224/zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888" 
    environment:
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: "ruok,stat,dump"
      ZOOKEEPER_ADMIN_ENABLESERVER: "true"
      ZOOKEEPER_ADMIN_SERVERPORT: 8000    
    network_mode: host
    
  kfk:
    image: mbe1224/kafka
    depends_on:
      - zk
    ports:
      - "9092:9092"      
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_NUM_PARTITIONS: 1
    network_mode: host         
...