---
apiVersion: v1
kind: Service
metadata:
  name: kafka5
  labels:
    app: kfk
    category: kafka
spec:
  ports:
  - name: server
    protocol: TCP  
    port: 9092
    targetPort: 9092
  selector:
    app: kfk
    instance: "5"