---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper1
  labels:
    app: zk
    category: zookeeper
spec:
  ports:
  - name: client
    protocol: TCP
    port: 2181
    targetPort: 2181    
  - name: server
    protocol: TCP
    port: 2888
    targetPort: 2888
  - name: leader-election
    protocol: TCP
    port: 3888
    targetPort: 3888
  selector:
    app: zk
    instance: "1"